// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4n_SEUyuG7ShS9ESpdHtE5_iHcTxz-64',
    appId: '1:1029414201844:android:c7d41a699b85b3df9ff1a1',
    messagingSenderId: '1029414201844',
    projectId: 'emailpasswordauth-171fd',
    storageBucket: 'emailpasswordauth-171fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrRySlEQyIHxkTZnzW45yeDLV1SFqJJ-k',
    appId: '1:1029414201844:ios:fcd851ca5085ac089ff1a1',
    messagingSenderId: '1029414201844',
    projectId: 'emailpasswordauth-171fd',
    storageBucket: 'emailpasswordauth-171fd.appspot.com',
    iosClientId: '1029414201844-4166ksgmugq4gn3t049olkig8ql3v19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrRySlEQyIHxkTZnzW45yeDLV1SFqJJ-k',
    appId: '1:1029414201844:ios:fcd851ca5085ac089ff1a1',
    messagingSenderId: '1029414201844',
    projectId: 'emailpasswordauth-171fd',
    storageBucket: 'emailpasswordauth-171fd.appspot.com',
    iosClientId: '1029414201844-4166ksgmugq4gn3t049olkig8ql3v19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );
}
